// Memory: durable facts that survive across sessions.
//
// One fact per file in memory/, plus a MEMORY.md index. The index is small
// enough to inline in every system prompt; the bodies are fetched with recall.
// Same progressive-disclosure trade as skills, for the same reason -- prompt
// tokens are the scarcest resource when you are decoding at single-digit t/s.
import { readFile, writeFile, readdir, rm, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { parseFrontMatter, oneLine } from './skills.mjs';

const TYPES = ['user', 'project', 'feedback', 'reference'];

const slug = (name) =>
  String(name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);

export class MemoryStore {
  constructor(dir) {
    this.dir = dir;
    this.indexPath = join(dir, 'MEMORY.md');
  }

  async list() {
    if (!existsSync(this.dir)) return [];
    const files = (await readdir(this.dir)).filter((f) => f.endsWith('.md') && f !== 'MEMORY.md');
    const out = [];
    for (const file of files) {
      const { meta, body } = parseFrontMatter(await readFile(join(this.dir, file), 'utf8'));
      out.push({
        name: meta.name || file.replace(/\.md$/, ''),
        description: meta.description || body.split('\n')[0].slice(0, 120),
        type: meta.type || 'project',
        file,
        body,
      });
    }
    return out.sort((a, b) => a.name.localeCompare(b.name));
  }

  async save({ name, description, type = 'project', content }) {
    if (!TYPES.includes(type)) type = 'project';
    const id = slug(name);
    if (!id) throw new Error('memory needs a name');
    await mkdir(this.dir, { recursive: true });
    // Front matter is single-line scalars; flatten a pasted paragraph so it
    // cannot forge keys or break the index.
    const text =
      `---\nname: ${id}\ndescription: ${oneLine(description)}\ntype: ${type}\n---\n\n${String(content).trim()}\n`;
    await writeFile(join(this.dir, `${id}.md`), text, 'utf8');
    await this.rebuildIndex();
    return id;
  }

  async get(name) {
    const all = await this.list();
    const hit = all.find((m) => m.name === slug(name) || m.name === name);
    if (!hit) {
      const names = all.map((m) => m.name).join(', ') || 'nothing remembered yet';
      throw new Error(`no memory named "${name}". Have: ${names}`);
    }
    return hit;
  }

  async forget(name) {
    const hit = await this.get(name);
    await rm(join(this.dir, hit.file));
    await this.rebuildIndex();
    return hit.name;
  }

  /** Regenerate MEMORY.md from the files, so the index cannot drift. */
  async rebuildIndex() {
    const all = await this.list();
    const lines = all.map((m) => `- [${m.name}](${m.file}) — ${m.description}`);
    const text = `# Memory index\n\nGenerated by the harness. One line per memory; read a body with the recall tool.\n\n${lines.join('\n')}\n`;
    await mkdir(this.dir, { recursive: true });
    await writeFile(this.indexPath, text, 'utf8');
  }

  /** The block that gets inlined into the system prompt. */
  async promptBlock({ enabled = true, types = null } = {}) {
    if (!enabled) return '';
    let all = await this.list();
    if (types) all = all.filter((m) => types.includes(m.type));
    if (!all.length) return '';
    const rows = all.map((m) => `- ${m.name} (${m.type}): ${m.description}`).join('\n');
    return `## Memory\n\nFacts you established in earlier sessions. Call recall with a name to read one in full.\n\n${rows}`;
  }
}

export function memoryTools(store) {
  return {
    remember: {
      mutates: true,
      schema: {
        description:
          'Store a durable fact for future sessions: a user preference, a project constraint, a correction the user gave you, or a pointer to an external resource. Do not store things the code already says.',
        parameters: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Short kebab-case identifier.' },
            description: { type: 'string', description: 'One line; this is what you see in the index next session.' },
            type: { type: 'string', enum: TYPES },
            content: { type: 'string', description: 'The fact itself, with the reasoning behind it.' },
          },
          required: ['name', 'description', 'content'],
        },
      },
      async run(args) {
        const id = await store.save(args);
        return `Remembered "${id}".`;
      },
    },
    recall: {
      schema: {
        description: 'Read a stored memory in full by name.',
        parameters: {
          type: 'object',
          properties: { name: { type: 'string' } },
          required: ['name'],
        },
      },
      async run({ name }) {
        const memory = await store.get(name);
        return `# ${memory.name} (${memory.type})\n\n${memory.body}`;
      },
    },
    forget: {
      mutates: true,
      schema: {
        description: 'Delete a memory that turned out to be wrong or obsolete.',
        parameters: {
          type: 'object',
          properties: { name: { type: 'string' } },
          required: ['name'],
        },
      },
      async run({ name }) {
        return `Forgot "${await store.forget(name)}".`;
      },
    },
  };
}
