// Skadi's pre-made launch profiles, tuned and measured on a 16 GB card
// (RX 9070 XT). They live in code rather than config/profiles.json so they ship
// with every release and cannot be edited in place: config.mjs overlays them on
// whatever the user has saved, and never writes them back. To change one, the
// user duplicates it -- the copy is an ordinary profile.
//
// A `serverExe` of "@name" is an engine, not a path: config.mjs resolves it
// against the `engines` table in profiles.json, and falls back to the main
// `serverExe` when the machine has no such engine registered.
//
// `info` is what the catalog page shows: perplexity (lower is better), measured
// decode speed, and a plain-language note. It is not passed to llama-server.
// An entry is matched to a model by its `model` file name, which is also how the
// model browser knows to badge a download as "has a Skadi profile".

export const CATALOG_VRAM_GB = 16;

export const PROFILE_CATALOG = Object.freeze({
  "qwen38-27b-iq3s-128k": {
    "label": "Qwen3.8-27B · IQ3_S + MTP · 128K · q5_1 cache",
    "model": "Qwen3.8-27B-GSQ-RCO-IQ3_S-mtp.gguf",
    "alias": "qwen3.8-27b-iq3_s-mtp-128k-fast",
    "device": "Vulkan0",
    "ctx": 131072,
    "ngl": 99,
    "ngld": 99,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q5_1",
    "cacheV": "q5_1",
    "kvUnified": true,
    "batch": 2048,
    "ubatch": 512,
    "fit": "off",
    "autoFit": "off",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": true,
    "specType": "draft-mtp",
    "specDraftNMax": 3,
    "specDraftPMin": 0.65,
    "vision": true,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "serverExe": "@beellama",
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "allowCpuLayers": false,
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "IQ3_S",
      "mtp": true,
      "engine": "BeeLlama",
      "repo": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
      "ppl": 3.63,
      "tps": [
        36,
        59
      ],
      "tier": "recommended",
      "note": "Recommended. The fastest option, and the same quality as the other IQ3_S profiles.",
      "kv": "q5_1",
      "ctx": 131072,
      "ctxLabel": "128K"
    }
  },
  "qwen38-27b-iq4xs-80k": {
    "label": "Qwen3.8-27B · IQ4_XS + MTP · 80K",
    "model": "Qwen3.8-27B-UD-IQ4_XS.gguf",
    "alias": "qwen3.8-27b-ud-iq4_xs",
    "device": "Vulkan0",
    "ctx": 80000,
    "ngl": 99,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q4_0",
    "cacheV": "q4_0",
    "kvUnified": true,
    "fit": "off",
    "parallel": 1,
    "batch": 2048,
    "ubatch": 512,
    "jinja": true,
    "useChatTemplate": true,
    "autoFit": "off",
    "fitPriority": "speed",
    "ctxFloor": 98304,
    "allowCpuLayers": true,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "medium",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "draftModel": "mtp-Qwen3.8-27B-Q4_0.gguf",
    "specType": "draft-mtp",
    "specDraftNMax": 3,
    "specDraftPMin": 0.65,
    "ngld": 99,
    "overrideTensor": null,
    "vision": true,
    "specDraftCacheK": "q4_0",
    "specDraftCacheV": "q4_0",
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "IQ4_XS",
      "mtp": true,
      "engine": "llama.cpp",
      "ppl": 3.59,
      "tps": [
        11,
        11
      ],
      "tier": "quality",
      "note": "Best quality, but the slowest and the shortest context.",
      "kv": "q4_0",
      "ctx": 80000,
      "ctxLabel": "80K",
      "repo": "unsloth/Qwen3.8-27B-GGUF"
    }
  },
  "qwen38-27b-q3kxl-120k": {
    "label": "Qwen3.8-27B · Q3_K_XL · 120K",
    "model": "Qwen3.8-27B-UD-Q3_K_XL.gguf",
    "alias": "qwen3.8-27b-ud-q3k-xl-96k",
    "ctx": 122880,
    "ngl": 30,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q8_0",
    "cacheV": "q8_0",
    "kvUnified": true,
    "fit": "on",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": true,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "device": "Vulkan0",
    "batch": 4096,
    "ubatch": 1024,
    "draftModel": "mtp-Qwen3.8-27B-Q4_0.gguf",
    "specType": "draft-mtp",
    "specDraftNMax": 3,
    "specDraftPMin": 0.65,
    "ngld": 99,
    "fitPriority": "speed",
    "allowCpuLayers": true,
    "ctxFloor": 98304,
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "vision": true,
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "Q3_K_XL",
      "mtp": false,
      "engine": "llama.cpp",
      "ppl": 3.61,
      "tps": [
        14,
        14
      ],
      "tier": "ok",
      "note": "Middle ground. MTP will not load with this quant.",
      "kv": "q8_0",
      "ctx": 122880,
      "ctxLabel": "120K",
      "repo": "unsloth/Qwen3.8-27B-GGUF"
    }
  },
  "qwen38-27b-iq3s-alt-128k": {
    "label": "Qwen3.8-27B · IQ3_S + MTP · 128K · kvarn4 cache",
    "model": "Qwen3.8-27B-GSQ-RCO-IQ3_S-mtp.gguf",
    "alias": "qwen3.8-27b-gsq-iq3_s-mtp-128k",
    "ctx": 128000,
    "ngl": 99,
    "ngld": 99,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "kvarn4",
    "cacheV": "kvarn4",
    "kvTailTokens": 2048,
    "kvUnified": true,
    "fit": "off",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": true,
    "specType": "draft-mtp",
    "specDraftNMax": 3,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "device": "Vulkan0",
    "serverExe": "@beellama",
    "autoFit": "off",
    "batch": 2048,
    "ubatch": 512,
    "vision": true,
    "specDraftPMin": 0.65,
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "IQ3_S",
      "mtp": true,
      "engine": "BeeLlama",
      "repo": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
      "ppl": 3.63,
      "tps": [
        15,
        15
      ],
      "tier": "ok",
      "note": "Uses the kvarn4 cache, which costs speed. The recommended profile is faster.",
      "kv": "kvarn4",
      "ctx": 128000,
      "ctxLabel": "128K"
    }
  },
  "qwen38-27b-iq3s-nomtp-128k": {
    "label": "Qwen3.8-27B · IQ3_S · 128K · kvarn4 cache",
    "model": "Qwen3.8-27B-GSQ-RCO-IQ3_S.gguf",
    "alias": "qwen3.8-27b-gsq-iq3_s-128k",
    "ctx": 128000,
    "ngl": 99,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "kvarn4",
    "cacheV": "kvarn4",
    "kvTailTokens": 2048,
    "kvUnified": true,
    "fit": "off",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": true,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "device": "Vulkan0",
    "serverExe": "@beellama",
    "autoFit": "off",
    "batch": 2048,
    "ubatch": 512,
    "vision": true,
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "IQ3_S",
      "mtp": false,
      "engine": "BeeLlama",
      "repo": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
      "ppl": 3.63,
      "tps": [
        14,
        14
      ],
      "tier": "ok",
      "note": "No MTP, so no speculative speedup.",
      "kv": "kvarn4",
      "ctx": 128000,
      "ctxLabel": "128K"
    }
  },
  "qwen38-27b-iq3xxs-120k": {
    "label": "Qwen3.8-27B · IQ3_XXS + MTP · 120K",
    "model": "Qwen3.8-27B-UD-IQ3_XXS.gguf",
    "alias": "qwen3.8-27b-ud-iq3_xxs-96k",
    "ctx": 122880,
    "ngl": 34,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q8_0",
    "cacheV": "q8_0",
    "kvOffload": true,
    "kvUnified": true,
    "fit": "on",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": true,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "extraArgs": [],
    "mmproj": "mmproj-Qwen3.8-27B-f16.gguf",
    "device": "Vulkan0",
    "batch": 4096,
    "ubatch": 1024,
    "draftModel": "mtp-Qwen3.8-27B-Q4_0.gguf",
    "specType": "draft-mtp",
    "specDraftNMax": 3,
    "specDraftPMin": 0.65,
    "ngld": 99,
    "fitPriority": "speed",
    "allowCpuLayers": true,
    "ctxFloor": 98304,
    "vision": true,
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.8-27B",
      "quant": "IQ3_XXS",
      "mtp": true,
      "engine": "llama.cpp",
      "ppl": 3.71,
      "tps": [
        20,
        20
      ],
      "tier": "weak",
      "note": "Beaten by IQ3_S on both speed and quality.",
      "kv": "q8_0",
      "ctx": 122880,
      "ctxLabel": "120K",
      "repo": "unsloth/Qwen3.8-27B-GGUF"
    }
  },
  "qwen36-35b-a3b-256k": {
    "label": "Qwen3.6-35B-A3B · Q4_K_XL · 256K",
    "model": "Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf",
    "alias": "qwen3.6-35b-a3b-q4_k_xl",
    "ngl": 41,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q8_0",
    "cacheV": "q8_0",
    "kvUnified": true,
    "fit": "on",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": false,
    "autoFit": "full",
    "fitPriority": "context",
    "ctxFloor": 65536,
    "allowCpuLayers": false,
    "extraArgs": [],
    "ctx": 262144,
    "batch": 4096,
    "ubatch": 1024,
    "ngld": 99,
    "specType": "draft-mtp",
    "specDraftNMax": 4,
    "specDraftPMin": 0.65,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "reasoningEffort": "xhigh",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "mmproj": "mmproj-Qwen3.6-35B-A3B-f16.gguf",
    "device": "Vulkan0",
    "overrideTensor": "blk\\.9\\.ffn_down.*=CPU,blk\\.10\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.11\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.12\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.13\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.14\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.15\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.16\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.17\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.18\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.19\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.20\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.21\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.22\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.23\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.24\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.25\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.26\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.27\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.28\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.29\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.30\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.31\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.32\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.33\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.34\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.35\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.36\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.37\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.38\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.39\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.40\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU",
    "vision": true,
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Qwen3.6-35B-A3B",
      "quant": "Q4_K_XL",
      "mtp": false,
      "engine": "llama.cpp",
      "ppl": 5.4,
      "tps": null,
      "tier": "weak",
      "note": "Outclassed by the 27B models.",
      "kv": "q8_0",
      "ctx": 262144,
      "ctxLabel": "256K"
    }
  },
  "ornith-35b-128k": {
    "label": "Ornith-35B · Q4_K_XL · 128K",
    "model": "Ornith-1.0-35B-UD-Q4_K_XL.gguf",
    "alias": "ornith-1.0-35b-q4_k_xl",
    "ngl": 41,
    "threads": 8,
    "threadsBatch": 16,
    "flashAttn": "on",
    "cacheK": "q8_0",
    "cacheV": "q8_0",
    "kvUnified": true,
    "fit": "on",
    "parallel": 1,
    "jinja": true,
    "useChatTemplate": false,
    "autoFit": "full",
    "fitPriority": "context",
    "ctxFloor": 65536,
    "allowCpuLayers": false,
    "extraArgs": [],
    "ctx": 131072,
    "batch": 4096,
    "ubatch": 1024,
    "reasoning": "on",
    "reasoningFormat": "deepseek",
    "reasoningPreserve": true,
    "chatTemplateKwargs": "{\"preserve_thinking\":true}",
    "temp": 1,
    "topK": 20,
    "topP": 0.95,
    "minP": 0,
    "repeatLastN": 4096,
    "repeatPenalty": 1.08,
    "device": "Vulkan0",
    "mmproj": "mmproj-Ornith-1.0-35B-f16.gguf",
    "overrideTensor": "blk\\.10\\.ffn_down.*=CPU,blk\\.11\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.12\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.13\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.14\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.15\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.16\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.17\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.18\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.19\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.20\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.21\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.22\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.23\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.24\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.25\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.26\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.27\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.28\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.29\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.30\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.31\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.32\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.33\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.34\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.35\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.36\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.37\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.38\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.39\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU,blk\\.40\\.ffn_(up|down|gate_up|gate)_(ch|)exps=CPU",
    "reasoningEffort": "xhigh",
    "vision": true,
    "catalog": true,
    "vramGB": 16,
    "info": {
      "family": "Ornith-35B",
      "quant": "Q4_K_XL",
      "mtp": false,
      "engine": "llama.cpp",
      "ppl": 5.14,
      "tps": null,
      "tier": "weak",
      "note": "Outclassed by the 27B models.",
      "kv": "q8_0",
      "ctx": 131072,
      "ctxLabel": "128K"
    }
  }
});

export const isCatalogId = (id) => Object.hasOwn(PROFILE_CATALOG, id);

/** Catalog profiles whose model file is `fileName` (case-insensitive), recommended first. */
export function catalogFor(fileName) {
  const wanted = String(fileName || '').toLowerCase();
  return Object.entries(PROFILE_CATALOG)
    .filter(([, p]) => String(p.model || '').toLowerCase() === wanted)
    .map(([id, p]) => ({ id, label: p.label, tier: p.info?.tier }));
}
